# Generated by Django 5.1.2 on 2025-02-22 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=50)),
                ('player_last_name', models.CharField(max_length=50)),
                ('player_email', models.EmailField(max_length=254)),
                ('player_age', models.IntegerField()),
                ('matches_played', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_manager_name', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.player')),
            ],
        ),
    ]
